version: '3'
services:
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: wiezmankimchi/nginx
    container_name: 54-nginx
    ports: 
      - "3080:80"
      - "443:443"
    environment:
      - DEV_DOMAIN=mxlinux.local
      - PASS=  
    networks: 
      - app-network
    depends_on:
      - "app"
  app:
    build:
        dockerfile: ./docker/app.dockerfile
        context: .
    image: wiezmankimchi/node
    container_name: 54-app
    ports:
      - "3054:3000"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks: 
      - app-network
networks:
    app-network:
        driver: bridge
